# Name that will be referenced do much more with it programmatically  
name: invoke-deploy 
on:
  repository_dispatch: 
    types: [deploy-service]
  workflow_dispatch: {}
jobs:
  test:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello there!"
      - name: Branch value
        run: echo "${{ github.event.client_payload.branch }}"


  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    if: always()
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Frontend
          - name: Backend
          - name: Database
    steps:
      - name: Setup
        id: setup
        run: |
          NAME_LOWER=$(echo "${{ matrix.name }}" | awk '{print tolower($0)}')
          echo "Matrix name: ${{ matrix.name }}"
          echo "NAME_LOWER: $NAME_LOWER"
          echo "::set-output name=name_lower::$NAME_LOWER"
          
          if [[ -z "${{ github.event.client_payload.branch }}"  ]]; then
            BRANCH_NAME=$(echo "$GITHUB_REF" | sed "s#refs/heads/##g")
          else
            BRANCH_NAME=$(echo ${{ github.event.client_payload.branch }} | sed "s#refs/heads/##g")            
          fi
            
          echo $BRANCH_NAME
          echo "::set-output name=branch_name::$BRANCH_NAME"

          mkdir publish
          
      - name: Release
        env: 
          BRANCH: ${{ steps.setup.outputs.branch_name }}
        run: |
          echo "Deploying branch: $BRANCH"
        
